### PR TITLE
feat(weekView): Allow drag outside calendar view

### PR DESCRIPTION
**Pull request by ElieSauveterre**
External events can be drag'n'drop from the calendar view to a drop zone

### CODE REVIEW

**Comment by mattlewis92** [comment]
Thanks for this! Rather than removing the old functionality can we retain the existing behaviour and have this opt in via an option like `[allowDragOutside]="true"`.

**Comment by ElieSauveterre** [comment]
@mattlewis92 It's done. What do you think ?

**Comment by mattlewis92** [comment]
@ElieSauveterre I've tweaked the logic so that if a user drags the event outside of the calendar view the event start and end dates are always changed by a fixed number of days rather than using the start and end of the week - what do you think?

**Comment by ElieSauveterre** [comment]
@mattlewis92 That's better. Thanks.

**Comment by mattlewis92** [comment]
Released as 0.16.0, thanks for the contribution! 👍

**Pull request merged**
