### PR TITLE
fix: use locale aware day view title for moment date formatter

### LINKED ISSUE #1396: calendarDate Pipe Incorrect for Day View When Using Moment
**Describe the bug**

When using `CalendarMomentDateFormatter` as the `dateFormatter` provider on the CalendarModule, the `calendarDate` Pipe returns "Friday, 21 January, 2021" instead of "Friday, January 21, 2021". 

**Minimal reproduction of the problem with instructions**

It is reproduced directly in the examples for the library
https://angular-calendar.com/#/moment

**Versions**

- `@angular/core`: 11.1.0
- `angular-calendar`:  0.29.0-beta.6
- Browser name and version: Chrome 87

### PR DESCRIPTION
**Pull request by JaxonWright**
Closes #1396

`dayViewTitle` changed to use `dddd, LL` formatting.

`dddd` = full day name (i.e Thursday)
`LL` = locale-dependent Month Day, Year (i.e January 21, 2021...but sometimes 21 January, 2021)

### CODE REVIEW

**Comment by mattlewis92** [comment]
Nice catch! Could you fix up the tests to match the new behaviour and then I will merge + release. Will probably release it on the `0.27.x` branch as it's technically a breaking change.

**Comment by JaxonWright** [comment]
@mattlewis92 test should be fixed

**Review by mattlewis92 — APPROVED** [review]
LGTM, thanks!

**Comment by mattlewis92** [comment]
Released as `0.29.0-beta.7`, thanks again!! 😄

**Pull request merged**
