### PR TITLE
fix: add missing SASS entry point

### LINKED ISSUE #1596: Can't import angular-calendar SASS files in an Angular project.
**Describe the bug**

Can't import library SASS files in an Angular project. Getting the following error:
```
SassError: Can't find stylesheet to import.
   ╷
12 │ @import "~angular-calendar/scss/angular-calendar";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/styles.scss 12:9  root stylesheet
```

**Minimal reproduction of the problem with instructions**

Create an empty Angular project that imports the SASS file in the app `styles.scss` by using:
```
@import "~angular-calendar/scss/angular-calendar";
```

**Versions**

- `@angular/core`: ^14.0.0
- `angular-calendar`: ^0.30.0

### PR DESCRIPTION
**Pull request by santam85**
This change would allow importing the sass files in Angular projects in the following fashion:
`@import "~angular-calendar/scss/angular-calendar";`
That is beneficial for plugins trying to find the critical path CSS, and allows to avoid having to hardcode a relative path to the `node_module`, simplifying adoption in monorepos with multiple projects.

Fixes #1596 and errors like:
```
SassError: Can't find stylesheet to import.
   ╷
12 │ @import "~angular-calendar/scss/angular-calendar";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/styles.scss 12:9  root stylesheet
```

Alternatively, this can be extended to all scss files by adding instead:
```
    "./scss/*" : {
      "sass": "./scss/*"
    },
```

**EDIT**
After some research and testing, I updated the PR to use the alternative approach shown above, looks like it's the one that has the best compatibility.

### CODE REVIEW

**Comment by adriatomas** [comment]
LGTM!

**Review by mattlewis92 — APPROVED** [review]
Awesome, thanks for the fix!!

**Comment by mattlewis92** [comment]
Released as `0.30.1`, please let me know if that works for you! 🙌

**Comment by santam85** [comment]
Yup thanks, works perfectly!

**Comment by h4k1m13or** [comment]
Hello @santam85 & @mattlewis92 
i was using this in `v0.28.28`:  `@import '~angular-calendar/scss/angular-calendar.scss';`, but it's not working in `v0.31.1`
any idea why ?

**Comment by mattlewis92** [comment]
> Hello @santam85 & @mattlewis92 i was using this in `v0.28.28`: `@import '~angular-calendar/scss/angular-calendar.scss';`, but it's not working in `v0.31.1` any idea why ?

I think it's because angular dropped support for the leading `~`, try `@import 'angular-calendar/scss/angular-calendar.scss';` instead

**Comment by h4k1m13or** [comment]
it workes, Thank you for the quick response

**Pull request merged**
