### PR TITLE
0.29.0

### PR DESCRIPTION
**Pull request by mattlewis92**
Hey folks! 👋 

Here's the changelog for the upcoming `0.29.0` release, it contains a few nice features as well as a couple of very small and easy to workaround breaking changes that should hopefully only impact a small minority of people.

You can try it out by doing: 
```
npm i angular-calendar@next
```

If you find any issues please let me know! 😄 

# Changelog

### Bug Fixes

* **week-view:** allow dragging events to span multiple days ([ef5749c](https://github.com/mattlewis92/angular-calendar/commit/ef5749c)), closes [#1234](https://github.com/mattlewis92/angular-calendar/issues/1234)

### Features

* **week-view:** add hourDuration option ([6a72448](https://github.com/mattlewis92/angular-calendar/commit/6a72448)), closes [#1080](https://github.com/mattlewis92/angular-calendar/issues/1080)
* **week-view:** add minimumEventHeight option ([7789fda](https://github.com/mattlewis92/angular-calendar/commit/7789fda)), closes [#1192](https://github.com/mattlewis92/angular-calendar/issues/1192)
* **week-view:** allow customising where events can be dragged ([cd12d3c](https://github.com/mattlewis92/angular-calendar/commit/cd12d3c)), closes [#1183](https://github.com/mattlewis92/angular-calendar/issues/1183)
* **week-view:** allow customising where events can be resized ([ba45051](https://github.com/mattlewis92/angular-calendar/commit/ba45051)), closes [#1183](https://github.com/mattlewis92/angular-calendar/issues/1183)
* add support for rtl ([caaf96c](https://github.com/mattlewis92/angular-calendar/commit/caaf96c)), closes [#1203](https://github.com/mattlewis92/angular-calendar/issues/1203)
* drop support for angular 6 and 7 ([bc15e03](https://github.com/mattlewis92/angular-calendar/pull/1249/commits/bc15e03459f2b1b5d0c8ef19304d109e4a285a28))

### BREAKING CHANGES

* angular 6, 7, 8, and 9 are no longer supported. To use this package you must upgrade to angular 10 or higher.
* **week-view:** the drag behaviour now mimicks the resize behaviour where you can drag an event down to move it into the next day. To restore the old behaviour you can use the new `validateEventTimesChanged` input to control where an event can be dragged.
* **week-view:** events on the week and day view will now always be at least 30 pixels high by default. To restore the old behaviour you can set `[minimumEventHeight]="1"`.

### CODE REVIEW

**Comment by mattlewis92** [comment]
[CU-4e2](http://localhost:9004/t/4e2) - test

**Comment by EFritzsche90** [comment]
Do you know when this will be finally be approved?

**Comment by mattlewis92** [comment]
> Do you know when this will be finally be approved?

It should be in the next couple of weeks, there's one more small breaking change I need to make first to ship the date adapters in ESM: https://github.com/mattlewis92/angular-calendar/issues/1283

**Comment by cheapfun** [comment]
Hello,

Thank you for considering my request: https://github.com/mattlewis92/angular-calendar/issues/1183!

I just tested this version, and it works pretty well, I could do anything I want, thank you!

Only one little bug:

Now an event can be moved "outside" the start and end times of the calendar. To fix this, I had to add a test in the validateEventTimesChanged method to check that the event is within the calendar limits, otherwise I return false.

**Comment by mattlewis92** [comment]
> Hello,
> 
> Thank you for considering my request: #1183!
> 
> I just tested this version, and it works pretty well, I could do anything I want, thank you!
> 
> Only one little bug:
> 
> Now an event can be moved outside the calendar. To fix this, I had to add a test in the validateEventTimesChanged method to check that the event is within the calendar limits (dayStartHour / dayEndHour).

Awesome, that's great to hear, I'm glad it worked for you 😄 

Regarding your issue I think this is expected behaviour, it's now completely opinionated where you can drag events to and is noted as a breaking change:

"week-view: the drag behaviour now mimicks the resize behaviour where you can drag an event down to move it into the next day. To restore the old behaviour you can use the new validateEventTimesChanged input to control where an event can be dragged."

**Comment by martijn19811** [comment]
Hi,

any idea when this will be approved?

**Comment by Julian-B90** [comment]
Hey i have install 0.29.0-beta.10 on our Project. We use the `mwl-calendar-week-view` and actual i ca not find an error.

**Comment by mattlewis92** [comment]
Apologies for the people that were waiting on this release, it was _long_ overdue (pandemic + burnout etc, it's a long story that I'm not going into here 😅), but `0.29.0` is now finally released as stable! 🥳

**Comment by billyjov** [comment]
Good Job @mattlewis92

**Pull request merged**
