### PR TITLE
0.28

### PR DESCRIPTION
**Pull request by mattlewis92**
Please try it today and give me feedback before the final release 🎉 

```
npm i angular-calendar@next
```

There are no more breaking changes planned for `0.28` unless something comes up while testing. The only thing the release is waiting on is to add schematics: https://github.com/mattlewis92/angular-calendar/issues/888

Changelog:
# [0.28.0](https://github.com/mattlewis92/angular-calendar/compare/v0.27.18...v0.28.0)

### Bug Fixes

* ensure compatibility with angular 9 and ivy ([d4fdfb3](https://github.com/mattlewis92/angular-calendar/commit/d4fdfb3a5e1668972821c84ab2808ec7866228b0)), closes [#1086](https://github.com/mattlewis92/angular-calendar/issues/1086)
* **day-view:** expand hour segments across the full calendar width ([61aef47](https://github.com/mattlewis92/angular-calendar/commit/61aef477233e22312278c7dc73cf15af56d9a8d1)), closes [#1083](https://github.com/mattlewis92/angular-calendar/issues/1083)
* **week-view:** prevent dropping external events on adjacent time slots ([494adb5](https://github.com/mattlewis92/angular-calendar/commit/494adb55576ed0b6dcdd23ef1b93c6eef1678b0b)), closes [#1062](https://github.com/mattlewis92/angular-calendar/issues/1062)

### Build System

* remove annotateForClosureCompiler option ([c23f54c](https://github.com/mattlewis92/angular-calendar/commit/c23f54cdec6078e25b82fabc2276f59f4303bcba))

### Features

* **schematics:** support ng add schematics ([2dc2f47](https://github.com/mattlewis92/angular-calendar/commit/2dc2f47421499f900f0e7ec9818ed05e113415a5)), closes [#888](https://github.com/mattlewis92/angular-calendar/issues/888)
* **day-view:** expose `allDayEventsLabelTemplate` input ([224848c](https://github.com/mattlewis92/angular-calendar/commit/224848c70df9aec7f6359f6e3990f39775e4c8a2))
* **week-view:** add current time marker ([d3872b1](https://github.com/mattlewis92/angular-calendar/commit/d3872b19580f990ac44af7cfb2ccfc013219680b)), closes [#1102](https://github.com/mattlewis92/angular-calendar/issues/1102)
* expose the click or keyboard event that triggers click handlers ([d1a2b78](https://github.com/mattlewis92/angular-calendar/commit/d1a2b785a6347f923edf22daa72beee85b5e89cd)), closes [#962](https://github.com/mattlewis92/angular-calendar/issues/962)
* **day-view:** merge the week and day view components ([2e92b25](https://github.com/mattlewis92/angular-calendar/commit/2e92b258f490f77f45202b2028b4a78f7fc5ddab)), closes [#889](https://github.com/mattlewis92/angular-calendar/issues/889)
* add accessibility support ([05c9a9a](https://github.com/mattlewis92/angular-calendar/commit/05c9a9a08918a44013f792f6cddd597255516813)), closes [#941](https://github.com/mattlewis92/angular-calendar/issues/941)
* upgrade date-fns to v2 ([d4d3873](https://github.com/mattlewis92/angular-calendar/commit/d4d3873048efc8e8d0624d0db70c5439a36c6627)), closes [#1064](https://github.com/mattlewis92/angular-calendar/issues/1064)

### BREAKING CHANGES

* **day-view:** If extending the root week view component to override the template you must make the following changes:

* Wrap the time events with `<div "class='cal-events-container'">`
* Change `<div class="cal-time-label-column" *ngIf="view.hourColumns.length > 0">` to `<div class="cal-time-label-column" *ngIf="view.hourColumns.length > 0 && daysInWeek !== 1">`
* Add `[isTimeLabel]="daysInWeek === 1"` to the bottom `<mwl-calendar-week-view-hour-segment>` elements
* **week-view:** if using a custom `headerTemplate` on the week view, then you must now add `let-dragEnter="dragEnter"` to the templates variables and `(dragEnter)="dragEnter.emit({ date: day.date })"` onto the `mwlDroppable` element.
* the `columnHeaderClicked` output on the month view now exposes an object instead of just the ISO day number

Before:
```
columnHeaderClicked="columnHeaderClicked($event)"
```

After:
```
columnHeaderClicked="columnHeaderClicked($event.isoDayNumber)"
```
* **day-view:** The day and week view have now merged. For most users this should be a seamless migration, however there are some edge cases that you may need to take account for:

Any custom styles you used for the day view will need to be adjusted. The `cal-day-view-theme` sass mixin is now gone as all the styles are shared between the week and day view.

The `eventWidth` option is removed, events now fill the available width.

If using `[daysInWeek]="1"` on the week view, the date and title formatters for the day view will be used instead.

The week view now has a border top applied to the top of the component container, rather than the top of the day headers container.

The `getDayView` and `getDayViewHourGrid` functions have been removed from the `CalendarUtils` service.

The following interfaces from `calendar-utils` were renamed: `DayViewHourSegment` -> `WeekViewHourSegment`, `DayViewHour` -> `WeekViewHour`, `DayViewEvent` -> `WeekViewTimeEvent`

The day view scheduler demo is now based off the week view instead, please check the updated demo code for how to migrate: https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler

If using a custom template for the `hourSegmentTemplate`, you must pass `let-isTimeLabel="isTimeLabel"` as a local variable and then change `<div class="cal-time">` to `<div class="cal-time" *ngIf="isTimeLabel">`
* the dist files are no longer annotated for usage with closure compiler.
* date-fns v2 or higher is now required as a peer dependency

If implementing a custom adapter, the `max` function signature has changed to accept an array of dates, instead of an infinite argument list.

The date adapters no longer accept strings as input arguments.

### CODE REVIEW

**Comment by mattlewis92** [comment]
> I just installed ` "angular-calendar": "^0.28.0-beta.3"` and `"date-fns": "^2.0.1"` and all is working well so far.

Awesome, thanks for testing! 😄

**Comment by mattlewis92** [comment]
> The only small thing I've noticed style wise is the outline being applied to all .cal-cell and .cal-event classes when focused. Easy to override but thought I'd point it out since it wasn't there in the past.

Yeah I noticed that as well, it's caused by the new accessibility stuff, I think it should be there by default and then you can just removed it yourself with `outline: 0`

> Everything checks out for me on `0.28.0-beta.3` and `date-fns 2.0.1` as well.

Awesome! 😄

**Comment by mattlewis92** [comment]
It sounds like you're missing `*ngIf="isTimeLabel"`?

**Comment by mattlewis92** [comment]
> I am also getting flooded by warnings saying:
> 
> > date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings.
> 
> As far as I can tell, I am not even using `date-fns` in my code. The problems seem to lie within `calendar-utils`.

Are you passing any strings as dates on events? e.g. `start: '2019-08-29T07:24:28.844Z'`

**Comment by kyleabens** [comment]
I noticed that the time slots on the left hand side on the day view are no longer clickable.  This is an issue for me because If I want to schedule an event which is set to begin at the same time as another event, I am unable to click a time since the existing event takes up the width of of that day.  If you would like me to make this a separate issue let me know.

**Comment by mattlewis92** [comment]
> I noticed that the time slots on the left hand side on the day view are no longer clickable. This is an issue for me because If I want to schedule an event which is set to begin at the same time as another event, I am unable to click a time since the existing event takes up the width of of that day. If you would like me to make this a separate issue let me know.

Nice catch! Yeah please make a separate issue and I'll get that fixed up

**Comment by kyleabens** [comment]
#1083

**Comment by mattlewis92** [comment]
Yeah sure, I'll see if there's a way of preserving it. 

Side note: having that many events on one line isn't really a great UX, I'd highly recommend grouping similar events and then when you click the group it shows all of them in popover or something (you can implement this via a [custom event template](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/day/calendar-day-view.component.ts#L308)). That might solve your problem better.

**Comment by rabidpaul** [comment]
I'll admit, this is somewhat of an edge-case. Grouping is definitely a UX improvement I'll suggest for this visualization. The templating system is very elegant to use to help work around issues like this.

**Comment by mattlewis92** [comment]
Ah, so I realised that displaying events on a fixed width won't actually work with drag and drop or resizing. So I think grouping events is the way to go to solve it, I just pushed up a new demo that shows you how you can go about doing it: https://mattlewis92.github.io/angular-calendar/#/group-similar-events

Screenshot 2019-10-19 at 13 32 54

**Comment by mattlewis92** [comment]
I just cut the rc release for `0.28`, please can people update to it and verify everything is working ok in their apps? If I don't get any issues reported then I will cut the final release a week from today 🎉

**Comment by mattlewis92** [comment]
`0.28` final is out! 🎉 Thanks again to everyone that contributed to and tested this release ❤️

**Comment by shalini-github** [comment]
major break!!! custom hourSegmentTemplate using async events not working from this version 0.28.0 - 0.28.16

**Pull request merged**
