### PR TITLE
chore: add support for custom container css class

### PR DESCRIPTION
**Pull request by Lucianovici**
This `cal-event-container` was not present in the older versions.
Let's add a way to customize it, similar to how we do it for the event itself (with `cssClass`).
Thanks!

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hi there, thanks for the PR, would you mind explaining a bit more about your use case for this? I'm just curious as I didn't imagine a situation where you would need to add a class on the container which is only used as a way of controlling drag + drop / resizing which shouldn't require any additional styling. Thanks!

**Comment by Lucianovici** [comment]
Hi @mattlewis92 
I have this kind of resource management panel with day views for each resource.

https://www.dropbox.com/s/wnygrddt5vsoesk/Screenshot%202017-08-03%2013.32.09.png?dl=0

There can be max two events at the same time, so they need to share the hour segment.
I can do it with event's `cssClass` alone, but the problem is that containers are overlapping, preventing the tooltip popup for one of the two events sharing the same hour segment, thus I need to have a way to adjust the container of the event.

Thanks.
PS: Is there a better way of accomplishing this?

**Comment by mattlewis92** [comment]
Ah ok that makes sense, thanks for taking the time to explain (also its super cool to see this lib being used in creative ways like this! 😄 ). I think it might be better if the event `cssClass` was just added directly to the events container element instead of the child event, as then you would still be able to target the child element with CSS. It's a breaking change, but nothing too painful to migrate.

**Comment by Lucianovici** [comment]
Indeed! Yeah it makes more sense to add it to the container. Would you like to make that change? Or should I? But then we need a way to migrate from the older versions, any suggestions?

**Comment by mattlewis92** [comment]
I've just cut `0.20.0` with this change, the migration is pretty straightforward, just a small change to the CSS selector 😄

**Comment by Lucianovici** [comment]
Great! Thank you. I appreciate. :)

**Pull request closed without merging**
