### PR TITLE
Support event listener and emitter on month calendar view on day header

### PR DESCRIPTION
**Pull request by agilob**
Closes https://github.com/mattlewis92/angular-calendar/issues/722

### CODE REVIEW

**Comment by agilob** [comment]
Cheers :)

**Comment by mattlewis92** [comment]
This is now in the latest 0.27 beta, you can install it with:
```
npm i angular-calendar@next
```

Let me know if you have any problems 😄

**Comment by agilob** [comment]
Is 0.27 going to be released any time soon?

**Comment by mattlewis92** [comment]
Hey, sorry I've been taking a break from open source lately, I have a couple more things I want to do for 0.27 but I'll try and release it asap. In the meantime it's always been available on the `next` tag on npm so you can use it in your app today, but I get that relying on unstable dist tags isn't ideal.

**Comment by agilob** [comment]
>but I get that relying on unstable dist tags isn't ideal.

not only this, we're not allowed to get unknown code to production, everything has to be released and signed.

**Pull request merged**
